name: ranker
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - cpuonly
  - pandas
  - pip
  - ipykernel
  - pip:
      - sentencepiece
      - optimum[onnxruntime]
      - fastapi==0.111.0
      - fasttext_wheel==0.9.2
      - huggingface_hub==0.24
      - lexicalrichness==0.5.1
      - numpy==1.26.4
      - pandas==2.2.2
      - pydantic==2.9
      - ranking_challenge==2.0.0
      - sentence_transformers==3.0.1
      - transformers==4.45.2
      - uvicorn==0.30.1
      - simplejson
      - numexpr
      - bottleneck
      - pytest